[package]
name = "postgres-interface"
edition.workspace    = true
version.workspace    = true
rust-version.workspace = true

[dependencies]
diesel          = { workspace = true }
diesel-async    = { workspace = true }
deadpool-diesel = { workspace = true }
futures-util    = { workspace = true }
tokio           = { workspace = true }
tracing         = { workspace = true }
thiserror       = { workspace = true }
uuid            = { workspace = true }
chrono          = { workspace = true }
async-trait     = { workspace = true }
node-enrollment = { workspace = true }
health-tracker  = { workspace = true }
