[package]
name = "agent-bin"
edition.workspace = true
version.workspace = true
rust-version.workspace = true

[[bin]]
name = "edr-agent"
path = "src/main.rs"

[dependencies]
agent-core = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true }
sd-notify = { workspace = true }
libc = { workspace = true }
toml = { workspace = true }
hostname = { workspace = true }
fleet-client = { workspace = true }
event-buffer = { workspace = true }
osquery-client = { workspace = true }
edr-sdk = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
agent-tracing = { workspace = true }
isolation = { workspace = true }
tokio-util = { workspace = true }
dotenvy = { workspace = true }
