[package]
name = "event-buffer"
edition.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
rusqlite = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
tempfile = { workspace = true }
